### ISSUE TITLE
errore apertura pagina admin

### ISSUE THREAD

**Issue by fsacchi74** [RedTurtle/redturtle.bandi#8]
Ciao,
abbiamo installato l'add-on su una 
versione con queste versioni:

Volto 13.8.2
Plone 5.2.4
CMF 2.5.0
Zope 4.5.5
Python 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]
PIL 6.2.2 (Pillow)

e dall'admin non si apre la pagina per l'inserimento di un nuovo contenuto.
L' errore segnalto è il seguente:

http://nuovoweb.comune.piacenza.it/api/@types/Bando
Traceback (innermost last):
Module ZPublisher.WSGIPublisher, line 162, in transaction_pubevents
Module ZPublisher.WSGIPublisher, line 371, in publish_module
Module ZPublisher.WSGIPublisher, line 274, in publish
Module ZPublisher.mapply, line 85, in mapply
Module ZPublisher.WSGIPublisher, line 63, in call_object
Module plone.rest.service, line 22, in __call__
Module plone.restapi.services, line 20, in render
Module design.plone.contenttypes.restapi.services.types.get, line 176, in reply
Module plone.restapi.services.types.get, line 106, in reply
Module plone.restapi.services.types.get, line 128, in reply_for_type
Module plone.restapi.types.utils, line 305, in get_info_for_type
Module plone.restapi.types.utils, line 256, in get_jsonschema_for_portal_type
Module plone.restapi.types.utils, line 220, in get_jsonschema_for_fti
Module plone.restapi.types.utils, line 172, in get_jsonschema_properties
Module zope.component._api, line 102, in getMultiAdapter
Module zope.component._api, line 116, in queryMultiAdapter
Module zope.interface.registry, line 365, in queryMultiAdapter
Module zope.interface.adapter, line 564, in queryMultiAdapter
Module plone.restapi.types.adapters, line 47, in __init__
Module zope.schema._field, line 768, in bind
Module zope.schema._field, line 466, in bind
Module zope.schema._field, line 454, in _resolve_vocabulary
zope.schema._field.MissingVocabularyError: Can't validate value without vocabulary named 'redturtle.bandi.destinatari.vocabulary'

I valori da admin dei campi ente, destinatari, tipi sono stati inseriti.

Grazie,
Federica

**Comment by cekk** [comment]
Ciao, ho appena provato con l'ultima versione disponibile (il master di git) e non ho problemi ad accedere a quell'endpoint.

L'errore che vedo, sembra legato al fatto che non trova un vocabolario (redturtle.bandi.destinatari.vocabulary) che però pare essere registrato bene [qui](https://github.com/RedTurtle/redturtle.bandi/blob/master/redturtle/bandi/configure.zcml#L68).
Vedo anche che nel traceback state usando design.plone.contenttypes quindi immagino che stiate provando un'installazione "completa" con anche volto.

Riesci a controllare se nel codice dei bandi vedi quel vocabolario registrato? Ci sono altri plugin installati che per caso potrebbero andarlo a nascondere/de-registrare?

**Comment by fsacchi74** [comment]
Il problema è stato risolto.
